<body>
<div id="root"></div>
<script src="https://unpkg.com/react@16.12.0/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom@16.12.0/umd/react-dom.development.js"></script>
<script src="https://unpkg.com/@babel/standalone@7.8.3/babel.js"></script>
<script src="https://unpkg.com/prop-types@15.6.1/prop-types.js"></script>
<script src="https://unpkg.com/react-error-boundary@1.2.5/dist/umd/react-error-boundary.js"></script>
<script type="text/babel">
	const ErrorBoundary = ReactErrorBoundary.ErrorBoundary

	function ErrorFallback({error}){
		return (
			<div>
				<p>Something went wrong</p>
				<p>{error.message}</p>
			</div>
		)
	}

	const Bomb = () => {
		throw new Error('Boom Boom')
	}

	const App = () => {
		const [explode, setExplode] = React.useState('')

		return (
			<div className="app-container">
				<div>
					<button onClick={() => setExplode(true)}>Boom</button>
				</div>
				<div>
					<ErrorBoundary FallbackComponent={ErrorFallback}>
						{explode ? <Bomb/> : 'Push the Boom!'}
					</ErrorBoundary>
				</div>
			< /div>
		)
	}

	ReactDOM.render(<App/>, document.getElementById('root'))
</script>
</body>
